### ISSUE TITLE
Fields not updating on pages

### ISSUE THREAD

**Issue by rfverde1** [alexvandervegt/advanced-custom-fields-widget#2]
Hey thanks for the plugin, I am trying to add it to one of my projects but I noticed that when I try to add a custom widget to a page the fields do not update. I tried to debug it and noticed that the "fields" array  is empty: when trying to iterate on the following code:
            foreach($new_instance["fields"] as $key => $value )

However when the widget is used by going through Preferences->widget the "fields"  array is there and the widget updates its values fine. The issue only seems to occur when using page builder on an actual page. 

Any clues why this might be?

**Comment by alexvandervegt** [comment]
Hi,

Did you know this plugin is adopted in ACF >= 5.0?

Please read my guide here on how to use it:

**Comment by rfverde1** [comment]
Thanks for the quick response, I did not know that it was adopted inAFC v5, that's fantastic! I assume once I get the v5 I will be able to use the custom widgets on the any page and not just the home page or footer?

**Comment by alexvandervegt** [comment]
Its also possible with this module, but there are many bugfixes in the current version of ACF. So I suggest you will use ACF 5
