### ISSUE TITLE
No dropdown to select custom widget

### ISSUE THREAD

**Issue by philJohnson** [alexvandervegt/advanced-custom-fields-widget#4]
I've added the Class extension in functions.php for the example widget however I can't select the new widget when adding custom fields in Rules. Is this plugin compatible with the latest version of ACF?

**Comment by alexvandervegt** [comment]
Hi Phil,

This module has been addopted by ACF, in version 5 it is not needed anymore.

On my guide you can read how to use the build-in version from ACF5

https://www.directbasing.com/resources/wordpress/advanced-custom-fields-widget/#create-kick-ass-widgets-with-acf

**Comment by philJohnson** [comment]
Thanks for that. I didn't notice that ACF 5 isn't the stable release just yet.
